In [2]:
import numpy as np
import pandas as pd

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

import seaborn as sns

In [6]:
df=pd.read_csv('Titanic_dataset_kaggle.csv')[['Age','Pclass','SibSp','Parch','Survived']]

In [7]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  34.5       3      0      0         0
1  47.0       3      1      0         1
2  62.0       2      0      0         0
3  27.0       3      0      0         0
4  22.0       3      1      1         1

In [8]:
df.dropna(inplace=True)

In [9]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  34.5       3      0      0         0
1  47.0       3      1      0         1
2  62.0       2      0      0         0
3  27.0       3      0      0         0
4  22.0       3      1      1         1

In [10]:
x=df.iloc[:,0:4]
y=df.iloc[:,-1]

In [11]:
x.head()

    Age  Pclass  SibSp  Parch
0  34.5       3      0      0
1  47.0       3      1      0
2  62.0       2      0      0
3  27.0       3      0      0
4  22.0       3      1      1

In [12]:
np.mean(cross_val_score(LogisticRegression(),x,y,scoring='accuracy',cv=20))

0.6238970588235293

# Applying Feature Constrution

In [14]:
x['Family_size']=x['SibSp'] + x['Parch'] + 1

In [15]:
x.head()

    Age  Pclass  SibSp  Parch  Family_size
0  34.5       3      0      0            1
1  47.0       3      1      0            2
2  62.0       2      0      0            1
3  27.0       3      0      0            1
4  22.0       3      1      1            3

In [16]:
def myfunc(num):
    if num == 1:
        #alone
        return 0
    elif num >1 and num <=4:
        # small family
        return 1
    else:
        # large family
        return 2

In [17]:
myfunc(4)

1

In [18]:
x['Family_type']=x['Family_size'].apply(myfunc)

In [19]:
x.head()

    Age  Pclass  SibSp  Parch  Family_size  Family_type
0  34.5       3      0      0            1            0
1  47.0       3      1      0            2            1
2  62.0       2      0      0            1            0
3  27.0       3      0      0            1            0
4  22.0       3      1      1            3            1

In [21]:
x.drop(columns=['SibSp','Parch','Family_size'],inplace=True)

In [23]:
np.mean(cross_val_score(LogisticRegression(),x,y,scoring='accuracy',cv=20))

0.6056985294117647

# Feature Splitting

In [24]:
df=pd.read_csv('Titanic_dataset_kaggle.csv')

In [25]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [26]:
df['Name']

0                                  Kelly, Mr. James
1                  Wilkes, Mrs. James (Ellen Needs)
2                         Myles, Mr. Thomas Francis
3                                  Wirz, Mr. Albert
4      Hirvonen, Mrs. Alexander (Helga E Lindqvist)
                           ...
413                              Spector, Mr. Woolf
414                    Oliva y Ocana, Dona. Fermina
415                    Saether, Mr. Simon Sivertsen
416                             Ware, Mr. Frederick
417                        Peter, Master. Michael J
Name: Name, Length: 418, dtype: object

In [27]:
df['Title'] = df['Name'].str.split(', ', expand=True)[1].str.split('.', expand=True)[0]
df['Name'].str.split(', ', expand=True)[1].str.split('.', expand=True)[0]

0          Mr
1         Mrs
2          Mr
3          Mr
4         Mrs
        ...
413        Mr
414      Dona
415        Mr
416        Mr
417    Master
Name: 0, Length: 418, dtype: object

In [28]:
df[['Title','Name']]

      Title                                          Name
0        Mr                              Kelly, Mr. James
1       Mrs              Wilkes, Mrs. James (Ellen Needs)
2        Mr                     Myles, Mr. Thomas Francis
3        Mr                              Wirz, Mr. Albert
4       Mrs  Hirvonen, Mrs. Alexander (Helga E Lindqvist)
..      ...                                           ...
413      Mr                            Spector, Mr. Woolf
414    Dona                  Oliva y Ocana, Dona. Fermina
415      Mr                  Saether, Mr. Simon Sivertsen
416      Mr                           Ware, Mr. Frederick
417  Master                      Peter, Master. Michael J

[418 rows x 2 columns]

In [30]:
df.groupby('Title')['Survived'].mean().sort_values(ascending=False)

Title
Dona      1.0
Miss      1.0
Mrs       1.0
Ms        1.0
Col       0.0
Dr        0.0
Master    0.0
Mr        0.0
Rev       0.0
Name: Survived, dtype: float64